resources:
  - name: dwpdigital-fly
    type: registry-image-resource
    source:
      repository: dwpdigital/fly
    check_every: 5m

  - name: ecr-dwpdigital-fly-dev
    .: (( inject meta.resources.ecr-resource ))
    source:
      repository: "fly"

  - name: ecr-dwpdigital-fly
    .: (( inject meta.resources.ecr-resource ))
    source:
      repository: "fly"
      aws_role_arn: arn:aws:iam::((dataworks.aws_management_acc)):role/ci

jobs:
  - name: mirror-dwpdigital-fly-dev
    serial_groups: [fly]
    plan:
      - get: dwpdigital-fly
        trigger: true
        params:
          format: oci
        attempts: 3
      - put: ecr-dwpdigital-fly-dev
        params:
          image: "dwpdigital-fly/image.tar"
        attempts: 3

  - name: mirror-dwpdigital-fly
    serial_groups: [fly]
    plan:
      - get: dwpdigital-fly
        trigger: true
        params:
          format: oci
        attempts: 3
      - put: ecr-dwpdigital-fly
        params:
          image: "dwpdigital-fly/image.tar"
        attempts: 3
