jobs:
  - name: fly-pr
    plan:
      - get: fly-pr
        trigger: true
        version: every
      - put: fly-pr
        params:
          path: fly-pr
          status: pending
      - .: (( inject meta.plan.terraform-bootstrap ))
        input_mapping:
          fly: fly-pr
      - .: (( inject meta.plan.terraform-plan ))
        input_mapping:
          fly: fly-pr
        params:
          TF_WORKSPACE: "management"
          DETAILED_EXITCODE: ""
        on_failure:
          put: fly-pr
          params:
            path: fly-pr
            status: failure
        on_success:
          put: fly-pr
          params:
            path: fly-pr
            status: success
